// sites/svelte-vite-svelte5-router/src/lib/paths/pages/List.svelte
<script lang="ts">
  import listData from "../../assets/listData.json" with { type: "json" };
  import List from "../../components/List.svelte";
</script>

<h1>Filterable list</h1>
<p>
  Nam pulvinar nisi a turpis sodales, id cursus purus malesuada. Mauris
  vestibulum mollis sapien, at ultrices arcu mollis quis. Nulla tempor nunc sed
  molestie suscipit. Aliquam egestas mollis sapien nec volutpat. Praesent vitae
  magna ut purus tristique posuere. Suspendisse eget lacus id nunc egestas
  aliquam. Sed urna urna, tristique in condimentum ac, molestie ac orci. Aenean
  lorem diam, condimentum nec nunc sed, maximus vulputate ante.
</p>
<List {listData} sticky={true} />
<p>
  Aliquam eget nulla at ipsum elementum mattis quis ac felis. Fusce imperdiet
  quam et dui vulputate, sit amet hendrerit lorem feugiat. Donec convallis
  bibendum ex. Proin lacinia tortor eu aliquet vulputate. Nam euismod ultrices
  erat, eget euismod risus tempus sed. Curabitur eu ipsum sollicitudin,
  elementum mauris luctus, hendrerit nunc. Mauris porttitor mi augue, id auctor
  arcu condimentum nec. Aenean finibus, leo at accumsan sollicitudin, velit est
  facilisis quam, et sagittis ligula nisi at mi.
</p>

// sites/solid-solid-start/src/routes/(base)/(pages)/list.tsx
import listData from "~/assets/listData.json" with { type: "json" };
import List from "~/components/List";

export default function ListPage() {
  return (
    <>
      <h1>Filterable list</h1>
      <p>
        Nam pulvinar nisi a turpis sodales, id cursus purus malesuada. Mauris
        vestibulum mollis sapien, at ultrices arcu mollis quis. Nulla tempor
        nunc sed molestie suscipit. Aliquam egestas mollis sapien nec volutpat.
        Praesent vitae magna ut purus tristique posuere. Suspendisse eget lacus
        id nunc egestas aliquam. Sed urna urna, tristique in condimentum ac,
        molestie ac orci. Aenean lorem diam, condimentum nec nunc sed, maximus
        vulputate ante.
      </p>
      <List listData={listData} sticky={true} />
      <p>
        Aliquam eget nulla at ipsum elementum mattis quis ac felis. Fusce
        imperdiet quam et dui vulputate, sit amet hendrerit lorem feugiat. Donec
        convallis bibendum ex. Proin lacinia tortor eu aliquet vulputate. Nam
        euismod ultrices erat, eget euismod risus tempus sed. Curabitur eu ipsum
        sollicitudin, elementum mauris luctus, hendrerit nunc. Mauris porttitor
        mi augue, id auctor arcu condimentum nec. Aenean finibus, leo at
        accumsan sollicitudin, velit est facilisis quam, et sagittis ligula nisi
        at mi.
      </p>
    </>
  );
}
