// sites/qwik-qwik-city/src/components/footer/footer.tsx
import { component$ } from "@builder.io/qwik";
import { Link } from "@builder.io/qwik-city";
import Links from "../links/links";
import styles from "./footer.module.css";

export default component$(() => {
  return (
    <footer class={[styles.footer]}>
      <div id="footer-content" class={[styles["footer-content"]]}>
        <Link href="/" id="footer-logo" class={[styles["footer-logo"]]}>
          Test site
        </Link>
        <ul>
          <Links />
        </ul>
        <blockquote class={[styles.blockquote]}>
          Sed blandit est nec quam vulputate, id vulputate ipsum scelerisque.
          Etiam in elit ornare, fermentum nisl vel, gravida ipsum.
        </blockquote>
      </div>
    </footer>
  );
});

// sites/preact-vite/src/components/footer/Footer.tsx
import Links from "../links/Links";
import s from "./Footer.module.css";

export default function Footer() {
  return (
    <footer className={s.footer}>
      <div id="footer-content">
        <a href="/" id="footer-logo">
          Test site
        </a>
        <ul>
          <Links />
        </ul>
        <blockquote>
          Sed blandit est nec quam vulputate, id vulputate ipsum scelerisque.
          Etiam in elit ornare, fermentum nisl vel, gravida ipsum.
        </blockquote>
      </div>
    </footer>
  );
}
