// sites/qwik-qwik-city/src/components/live/live.tsx
import { component$, useSignal, useVisibleTask$ } from "@builder.io/qwik";
import liveData from "~/assets/liveData.json" with { import: "json" };
import styles from "./live.module.css";

const INTERVAL = 800;

export default component$(() => {
  const index = useSignal(0);

  useVisibleTask$(() => {
    let timeoutId: number | NodeJS.Timeout;
    function stepData() {
      index.value = (index.value + 1) % (liveData.length);
      timeoutId = setTimeout(stepData, INTERVAL);
    }
    stepData();
    return () => {
      clearTimeout(timeoutId);
    };
  });

  return (
    <table id="live-data" class={[styles["live-data"]]}>
      <tbody>
        <tr>
          <td>{liveData?.[index.value]?.[0]}</td>
          <td>{liveData?.[index.value]?.[1]}</td>
          <td>{liveData?.[index.value]?.[2]}</td>
        </tr>
      </tbody>
    </table>
  );
});

// sites/preact-vite/src/components/live/Live.tsx
import liveData from "../../assets/liveData.json" with { type: "json" };
import { computed, useSignal } from "@preact/signals";
import s from "./Live.module.css";

export default function Live() {
  const INTERVAL = 1000 as const;

  const index = useSignal(0);

  computed(() => {
    let timeoutId: number | NodeJS.Timeout;
    function stepData() {
      index.value = (index.value + 1) % (liveData.length - 1);
      timeoutId = setTimeout(stepData, INTERVAL);
    }
    stepData();
    return () => {
      clearTimeout(timeoutId);
    };
  });

  return (
    <table id="live-data" className={s.liveData}>
      <tbody>
        <tr>
          <td>{liveData?.[index.value]?.[0]}</td>
          <td>{liveData?.[index.value]?.[1]}</td>
          <td>{liveData?.[index.value]?.[2]}</td>
        </tr>
      </tbody>
    </table>
  );
}
