// sites/qwik-qwik-city/src/components/header/header.tsx
import { component$ } from "@builder.io/qwik";
import { Link } from "@builder.io/qwik-city";
import Links from "../links/links";
import favicon from "~/assets/favicon.svg";
import styles from "./header.module.css";

export default component$(() => {
  return (
    <>
      <header class={[styles.header]}>
        <nav>
          <ul>
            <li>
              <Link href="/">
                <img
                  id="icon"
                  class={[styles.icon]}
                  src={favicon}
                  alt="Front page"
                />
              </Link>
            </li>
            <Links />
          </ul>
        </nav>
      </header>
    </>
  );
});

// sites/react-react-router-framework/app/components/header/Header.tsx
import { Link } from "react-router";
import Links from "@/components/links/Links";
import s from "./Header.module.css";

export default function Header() {
  return (
    <header className={s.header}>
      <nav>
        <ul>
          <li>
            <Link to="/">
              <img
                id={`icon`}
                className={s.icon}
                src={"/icon.svg"}
                alt="Front page"
                loading="lazy"
              />
            </Link>
          </li>
          <Links />
        </ul>
      </nav>
    </header>
  );
}
