// sites/solid-solid-start/src/components/Links.tsx
import { For } from "solid-js";
import { A } from "@solidjs/router";
import { pages } from "~/assets/pages";

export default function Links() {
  return (
    <For each={[...pages.entries()]}>
      {([path, name]) => (
        <li>
          <A href={path}>{name}</A>
        </li>
      )}
    </For>
  );
}

// sites/qwik-qwik-city/src/components/links/links.tsx
import { component$ } from "@builder.io/qwik";
import { Link } from "@builder.io/qwik-city";
import { pages } from "~/assets/pages";

export default component$(() => {
  return (
    <>
      {[
        ...pages.entries().map(([path, name]) => (
          <li key={path}>
            <Link href={path}>{name}</Link>
          </li>
        )),
      ]}
    </>
  );
});
