// sites/svelte-svelte5-router/src/lib/paths/pages/FAQ.svelte
<script lang="ts">
  import Details from "../../components/details.svelte";
</script>

<h1>Expandable FAQ</h1>
<p>
  Praesent interdum ante et lacus eleifend eleifend eget quis felis. Sed at
  lacus quis tortor iaculis commodo. Curabitur quis sem velit. Aliquam ut
  egestas diam, sed blandit velit. Sed viverra iaculis velit at luctus.
  Suspendisse convallis porta felis vitae tincidunt. Proin tempus dui vel
  aliquam mollis. Mauris lacus mi, hendrerit et pretium et, consectetur vel
  tortor. Maecenas facilisis feugiat erat in ornare. Duis elementum tempus
  laoreet.
</p>
<Details summary="Cras venenatis luctus urna non pulvinar?">
  <p>
    Nunc tincidunt tincidunt molestie. Aenean porta at erat et volutpat.
    Curabitur justo libero, eleifend nec placerat a, semper sit amet nulla.
    Nullam lacus risus, ornare vel tellus sed, iaculis viverra lectus. Maecenas
    tincidunt dolor lacinia, congue erat ut, condimentum neque. Fusce
    vestibulum, mauris a varius tristique, purus mauris dapibus justo, eget
    finibus mauris mauris ac ante. Morbi id bibendum turpis.
  </p>
</Details>
<Details summary="Nulla vel mauris sed libero ultricies blandit?">
  <p>
    Nulla augue nisl, cursus ac eros et, venenatis sodales nisl. Fusce diam ex,
    feugiat quis diam quis, eleifend sodales risus. Integer enim quam, efficitur
    dapibus eleifend a, posuere id felis. Suspendisse vulputate mollis leo.
    Aenean leo tellus, pharetra eget urna vel, malesuada tristique ante. Donec
    laoreet, justo vitae consectetur accumsan, ipsum sem bibendum mauris, id
    malesuada purus urna non lorem. Vestibulum ut massa a nibh vestibulum
    vestibulum vel vel nunc. Morbi sodales vitae nibh laoreet egestas. Morbi sit
    amet vestibulum mauris, non vulputate magna. Aliquam convallis vestibulum
    fringilla. Nullam faucibus ipsum massa, vitae molestie magna gravida sit
    amet. Nunc a quam bibendum, egestas ipsum a, finibus dui. Nulla turpis
    dolor, iaculis at nisi non, suscipit luctus ante. Donec faucibus quam in
    odio ullamcorper, non ultricies sem sodales.
  </p>
</Details>
<Details summary="Vestibulum pulvinar sollicitudin euismod?">
  <p>
    Sed scelerisque enim ultrices mauris viverra, eget suscipit libero volutpat.
    Vivamus ut bibendum elit. Vestibulum ante ipsum primis in faucibus orci
    luctus et ultrices posuere cubilia curae; Vestibulum ante ipsum primis in
    faucibus orci luctus et ultrices posuere cubilia curae; Morbi justo dui,
    faucibus in tincidunt a, lacinia ut felis. Integer posuere, urna quis
    sollicitudin convallis, nunc nunc finibus arcu, ac hendrerit nibh diam eget
    lacus. Vivamus pellentesque ac sem ut lacinia. Aliquam bibendum tortor nibh,
    et imperdiet libero ullamcorper non. Sed bibendum id justo non porta. Donec
    tempor maximus metus sit amet auctor. Quisque risus nulla, fringilla vel
    turpis at, gravida vestibulum dolor.
  </p>
</Details>
<Details summary="Praesent fringilla mollis nunc nec vehicula?">
  <p>
    Etiam mauris velit, molestie a egestas nec, volutpat hendrerit nunc. Duis a
    eros euismod est tincidunt rutrum pretium vel mauris. Praesent risus est,
    condimentum ac elit a, maximus faucibus nisi. Pellentesque elementum
    ullamcorper tellus eget pellentesque. Donec nec arcu tellus. Aliquam sit
    amet auctor ligula. Morbi neque lorem, scelerisque nec volutpat sit amet,
    tincidunt et erat. Integer pharetra justo non purus vehicula, ut porttitor
    nisi rutrum. Fusce eget gravida leo. Curabitur sit amet augue lorem. Aliquam
    augue ante, posuere eget malesuada in, volutpat vitae erat. Pellentesque
    imperdiet ipsum a sapien aliquam hendrerit. Proin diam ipsum, vulputate
    vitae purus vel, rhoncus vehicula turpis. Donec porttitor vitae tellus
    aliquet malesuada. Morbi luctus diam ac posuere bibendum. In aliquam felis
    non velit finibus hendrerit.
  </p>
</Details>
<Details summary="Aliquam id elit ullamcorper erat tempus volutpat?">
  <p>
    Aenean rutrum dictum tortor eget tempus. Vestibulum congue molestie neque
    sit amet suscipit. Nulla vel ornare nunc. Integer dignissim ipsum et urna
    auctor faucibus. Vestibulum ultricies volutpat purus, at consequat elit
    scelerisque sit amet. Sed sit amet convallis nisi. Quisque gravida, magna
    eget laoreet vulputate, nisi diam tincidunt ipsum, ac varius mauris purus
    eget nisl. Duis magna eros, ornare nec est eu, ullamcorper tincidunt ante.
    Phasellus risus ante, ullamcorper eu erat eu, blandit accumsan mauris.
    Praesent nulla ligula, varius vitae eros a, aliquet semper tellus.
  </p>
</Details>
<Details summary="Morbi iaculis ex ut nulla ullamcorper mollis?">
  <p>
    Nulla quis pulvinar leo, vitae rhoncus ex. Proin congue leo pharetra
    dignissim porta. Nullam urna libero, tristique vel risus vel, iaculis cursus
    neque. Donec scelerisque ligula ex, eget congue augue pretium et. Nulla
    dapibus sollicitudin tortor. Praesent finibus vitae dui non aliquet. In
    sollicitudin nisi at risus feugiat laoreet. Duis sit amet blandit diam, non
    congue ligula. Etiam sit amet nunc elementum, porttitor neque et, tempus
    nibh.
  </p>
</Details>
<Details summary="Mauris iaculis sagittis arcu?">
  <p>
    Vestibulum fringilla egestas turpis ut aliquet. Praesent vel viverra lectus,
    nec pharetra libero. Pellentesque leo nisi, elementum quis blandit nec,
    vulputate et enim. Sed venenatis sodales massa, in varius magna mattis sed.
    Pellentesque lectus eros, sagittis aliquet urna a, interdum euismod tortor.
    Etiam gravida sed libero eget porta. Duis non lacus justo. Donec dictum erat
    et sapien interdum aliquam. Sed mollis luctus dui, id tempus justo cursus
    eu. Cras vel scelerisque ipsum. In hac habitasse platea dictumst.
    Pellentesque tempus erat vel eleifend pharetra. Vivamus egestas et justo
    pulvinar bibendum. Curabitur est enim, ornare ac porttitor ut, venenatis in
    diam. Donec sodales in nulla sed ultrices.
  </p>
</Details>
<Details summary="Suspendisse finibus ultricies justo eu tristique?">
  <p>
    In vehicula, lorem sed convallis euismod, turpis nulla aliquam nisi, a
    ullamcorper lacus lectus eu leo. Nunc pharetra ullamcorper rutrum. Praesent
    placerat, nisi ut pulvinar efficitur, lacus arcu sagittis lacus, non
    eleifend odio erat a lorem. Duis sed ipsum sed ex finibus imperdiet in ut
    est. Sed suscipit, justo id sodales elementum, sem nunc convallis nisi, non
    cursus sem lectus et nulla. Phasellus tristique dolor quis mi tempus
    blandit. Mauris velit urna, auctor maximus blandit vitae, pharetra in
    turpis. Phasellus volutpat condimentum ullamcorper. Proin sit amet velit
    ipsum. Pellentesque sagittis, ante nec dignissim viverra, mauris eros
    posuere sapien, eu lobortis ex turpis vel metus. Nulla facilisi. Etiam in
    dapibus eros.
  </p>
</Details>
<Details summary="Aenean nec condimentum diam?">
  <p>
    Ut rutrum eros vehicula rutrum pretium. Maecenas luctus nunc sed sem
    imperdiet luctus. Nam sollicitudin nisl ac ligula auctor, mattis tempor
    turpis feugiat. Suspendisse iaculis, nunc nec porttitor tincidunt, tortor
    mauris luctus quam, ac facilisis odio lorem non diam. Fusce fringilla ex id
    dui luctus, at facilisis purus consectetur. Pellentesque vulputate at ipsum
    vitae condimentum. Donec sollicitudin elit id efficitur accumsan. Sed eu
    tempor arcu. Suspendisse nibh eros, vulputate ultricies purus id, faucibus
    tincidunt tortor. Mauris pellentesque aliquet rhoncus. Maecenas rutrum sem
    quis leo consequat, in volutpat lacus iaculis. Class aptent taciti sociosqu
    ad litora torquent per conubia nostra, per inceptos himenaeos. In hac
    habitasse platea dictumst. Aenean hendrerit hendrerit quam. Cras orci nibh,
    sollicitudin ac nunc sed, accumsan luctus sem.
  </p>
</Details>
<Details summary="Nullam volutpat nulla in tristique venenatis?">
  <p>
    Suspendisse tempus mauris ac libero molestie sagittis gravida nec sem. Morbi
    porttitor dictum est, sit amet tristique nunc efficitur fermentum. Morbi
    pretium laoreet nulla, dictum tempus quam finibus vel. Sed ut vehicula
    ipsum, at accumsan nibh. Fusce ac felis lectus. Cras malesuada a dui eget
    congue. Aenean felis massa, lobortis ac placerat ac, malesuada sed leo. In
    ultricies metus vitae pharetra pulvinar. Nullam cursus consequat lorem,
    gravida pulvinar magna tempus id.
  </p>
</Details>
<Details summary="Nulla facilisi?">
  <p>
    Aliquam consequat non lorem in tempor. Etiam felis erat, blandit ac interdum
    ut, luctus at quam. Pellentesque auctor odio id urna rhoncus, ut cursus mi
    hendrerit. Donec in massa non magna varius dignissim sit amet id lectus.
    Etiam mollis mollis finibus. Cras non metus mauris. Nullam facilisis
    consectetur purus, porttitor tincidunt augue.
  </p>
</Details>
<Details summary="Maecenas et placerat sapien?">
  <p>
    Ut volutpat ligula in velit aliquet bibendum. Nulla facilisi. Vivamus eget
    condimentum nulla, non ultricies turpis. Nullam pharetra odio ante, eget
    malesuada justo pretium eget. Pellentesque diam nisi, tincidunt nec purus
    at, dapibus vehicula magna. Sed id turpis nulla. Nulla facilisi.
    Pellentesque congue blandit laoreet. Cras at pellentesque nibh, ac
    vestibulum magna. Curabitur viverra, lectus non maximus sodales, velit
    tortor faucibus sapien, id sagittis leo massa id libero. Cras ac risus eget
    massa dictum fringilla. Mauris pretium nunc risus, vitae lobortis lectus
    placerat eu. Nulla facilisi. In hac habitasse platea dictumst. Duis vel
    lectus eros.
  </p>
</Details>
<Details summary="Mauris pharetra scelerisque nulla sit amet fringilla?">
  <p>
    Morbi sed egestas dolor, in vehicula magna. Suspendisse ullamcorper elit in
    tellus faucibus dignissim. Aliquam urna tellus, porttitor in dignissim at,
    consequat id urna. Donec auctor purus id nunc scelerisque, quis malesuada
    orci scelerisque. Vestibulum tempus imperdiet dolor, et suscipit erat
    scelerisque sed. Vestibulum dictum massa ut enim condimentum accumsan.
    Vestibulum feugiat congue nulla eu aliquet. Donec quam ligula, venenatis sed
    sem eu, facilisis maximus turpis. Sed malesuada dictum urna, sed imperdiet
    ex accumsan a. Vestibulum ante ipsum primis in faucibus orci luctus et
    ultrices posuere cubilia curae;
  </p>
</Details>
<Details summary="Quisque consectetur varius nibh?">
  <p>
    Suspendisse sit amet tortor elementum, ultrices lorem quis, luctus nisi.
    Nulla quis volutpat ex. Duis quis justo at nisi tincidunt sodales sed nec
    urna. Duis interdum risus at congue tristique. Pellentesque habitant morbi
    tristique senectus et netus et malesuada fames ac turpis egestas. Nullam ac
    dolor non nulla vestibulum elementum. Morbi ut mi sit amet enim tincidunt
    rutrum laoreet a urna. Vivamus at leo at nisl laoreet placerat. Sed a odio
    orci. Aenean gravida efficitur lectus quis fringilla. Pellentesque
    ullamcorper sodales risus, ac consequat tortor pretium id. Pellentesque
    habitant morbi tristique senectus et netus et malesuada fames ac turpis
    egestas. Duis tortor quam, commodo et sagittis ac, eleifend eget tortor. In
    a luctus elit. Donec quis nunc massa. Phasellus non ex lobortis, tincidunt
    nunc commodo, blandit odio.
  </p>
</Details>
<Details summary="Cras nec consequat nibh, id posuere nibh?">
  <p>
    Vestibulum tempus magna non aliquam pulvinar. Nam vestibulum nisi non
    aliquet lacinia. Praesent viverra cursus rhoncus. In hac habitasse platea
    dictumst. Quisque fringilla diam ac dui placerat, quis cursus turpis
    lobortis. Aenean sit amet quam tristique, auctor elit ut, porttitor magna.
    Quisque rhoncus posuere neque, ut elementum orci porta nec. In pharetra
    mollis volutpat. Fusce ullamcorper a quam quis faucibus. Ut varius, tortor
    id molestie mollis, lacus felis ultrices risus, imperdiet viverra massa
    libero in massa. Suspendisse maximus odio ac nisi posuere vehicula. Nunc
    hendrerit volutpat velit, non laoreet nibh laoreet sed.
  </p>
</Details>
<Details summary="Integer ut massa enim?">
  <p>
    Ut eget gravida dui. Sed eu commodo neque. Cras varius augue eu efficitur
    cursus. Cras tristique metus quis nibh finibus, nec ultrices nulla sagittis.
    Sed ac faucibus lectus. Sed interdum, risus id feugiat laoreet, ligula quam
    dignissim libero, in finibus dolor metus eget orci. Vivamus tristique odio
    id sapien mollis, et lacinia sapien pellentesque. Vivamus id bibendum ex.
    Aenean ut vehicula urna. Ut eu posuere nisi. Pellentesque habitant morbi
    tristique senectus et netus et malesuada fames ac turpis egestas. Nulla in
    ligula sem. Mauris in lorem scelerisque, tincidunt arcu ut, scelerisque
    mauris.
  </p>
</Details>
<Details summary="Nam maximus magna at lacinia mollis?">
  <p>
    Mauris at sem a risus laoreet semper. Pellentesque eu tempus nibh, et
    maximus arcu. Aenean eleifend tellus eu neque scelerisque, in feugiat ipsum
    convallis. Donec maximus quam lacus, vel maximus metus placerat at. Ut orci
    quam, lobortis a ante nec, sollicitudin condimentum neque. Curabitur aliquet
    sem eget scelerisque faucibus. Ut tempus risus orci, a rutrum metus vehicula
    eget. Morbi in euismod velit, sed tristique enim. Pellentesque eget metus
    rutrum sapien elementum pulvinar.
  </p>
</Details>
<Details summary="Mauris bibendum justo eu eleifend efficitur?">
  <p>
    Integer rutrum sollicitudin ipsum. Suspendisse eget gravida ipsum, sed
    suscipit orci. Nunc convallis faucibus aliquet. Sed porttitor ultricies
    aliquet. Duis id est ante. Nulla tellus libero, sollicitudin id eros eget,
    sagittis commodo tortor. Praesent posuere massa non tincidunt gravida.
    Vestibulum sit amet quam ut nisl laoreet euismod sit amet quis diam.
    Maecenas id nunc efficitur, vestibulum quam a, rutrum mi. Pellentesque
    porttitor nisl mauris. Vestibulum porta enim nibh, aliquam malesuada diam
    tincidunt et. Nam varius tristique fringilla. Proin pretium sapien dolor, ac
    ornare lacus luctus ut. Donec imperdiet metus ac aliquet fermentum. Proin
    aliquet ex ut porta luctus. Curabitur velit urna, fermentum at turpis vitae,
    mattis congue lorem.
  </p>
</Details>
<Details summary="Pellentesque quis feugiat tellus?">
  <p>
    In hac habitasse platea dictumst. Sed non lacus sed leo vulputate tincidunt.
    Donec sodales velit et sapien congue commodo. Phasellus turpis ipsum,
    porttitor ac commodo nec, sollicitudin a orci. Maecenas auctor neque nibh,
    quis pretium odio venenatis in. Pellentesque non porta lorem. Morbi et massa
    eget nulla sollicitudin tincidunt fermentum vitae enim. Sed ut maximus diam,
    interdum mattis est. Mauris cursus risus ut nulla commodo aliquet. Morbi id
    diam diam. Donec est urna, gravida sed mauris eu, scelerisque tincidunt
    risus. Sed aliquet odio non lacus venenatis, quis dapibus dolor cursus.
    Vestibulum rhoncus, odio facilisis volutpat vulputate, ex quam porttitor
    nisl, nec imperdiet orci orci at mauris. Integer ac placerat augue, et
    commodo libero. In a magna ac ex vehicula laoreet et in lacus. Integer eget
    metus justo.
  </p>
</Details>

// sites/react-nextjs/src/app/(pages)/faq/page.tsx
import Details from "@/components/Details";

export default function Page() {
  return (
    <>
      <h1>Expandable FAQ</h1>
      <p>
        Praesent interdum ante et lacus eleifend eleifend eget quis felis. Sed
        at lacus quis tortor iaculis commodo. Curabitur quis sem velit. Aliquam
        ut egestas diam, sed blandit velit. Sed viverra iaculis velit at luctus.
        Suspendisse convallis porta felis vitae tincidunt. Proin tempus dui vel
        aliquam mollis. Mauris lacus mi, hendrerit et pretium et, consectetur
        vel tortor. Maecenas facilisis feugiat erat in ornare. Duis elementum
        tempus laoreet.
      </p>
      <Details summary="Cras venenatis luctus urna non pulvinar?">
        <p>
          Nunc tincidunt tincidunt molestie. Aenean porta at erat et volutpat.
          Curabitur justo libero, eleifend nec placerat a, semper sit amet
          nulla. Nullam lacus risus, ornare vel tellus sed, iaculis viverra
          lectus. Maecenas tincidunt dolor lacinia, congue erat ut, condimentum
          neque. Fusce vestibulum, mauris a varius tristique, purus mauris
          dapibus justo, eget finibus mauris mauris ac ante. Morbi id bibendum
          turpis.
        </p>
      </Details>
      <Details summary="Nulla vel mauris sed libero ultricies blandit?">
        <p>
          Nulla augue nisl, cursus ac eros et, venenatis sodales nisl. Fusce
          diam ex, feugiat quis diam quis, eleifend sodales risus. Integer enim
          quam, efficitur dapibus eleifend a, posuere id felis. Suspendisse
          vulputate mollis leo. Aenean leo tellus, pharetra eget urna vel,
          malesuada tristique ante. Donec laoreet, justo vitae consectetur
          accumsan, ipsum sem bibendum mauris, id malesuada purus urna non
          lorem. Vestibulum ut massa a nibh vestibulum vestibulum vel vel nunc.
          Morbi sodales vitae nibh laoreet egestas. Morbi sit amet vestibulum
          mauris, non vulputate magna. Aliquam convallis vestibulum fringilla.
          Nullam faucibus ipsum massa, vitae molestie magna gravida sit amet.
          Nunc a quam bibendum, egestas ipsum a, finibus dui. Nulla turpis
          dolor, iaculis at nisi non, suscipit luctus ante. Donec faucibus quam
          in odio ullamcorper, non ultricies sem sodales.
        </p>
      </Details>
      <Details summary="Vestibulum pulvinar sollicitudin euismod?">
        <p>
          Sed scelerisque enim ultrices mauris viverra, eget suscipit libero
          volutpat. Vivamus ut bibendum elit. Vestibulum ante ipsum primis in
          faucibus orci luctus et ultrices posuere cubilia curae; Vestibulum
          ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia
          curae; Morbi justo dui, faucibus in tincidunt a, lacinia ut felis.
          Integer posuere, urna quis sollicitudin convallis, nunc nunc finibus
          arcu, ac hendrerit nibh diam eget lacus. Vivamus pellentesque ac sem
          ut lacinia. Aliquam bibendum tortor nibh, et imperdiet libero
          ullamcorper non. Sed bibendum id justo non porta. Donec tempor maximus
          metus sit amet auctor. Quisque risus nulla, fringilla vel turpis at,
          gravida vestibulum dolor.
        </p>
      </Details>
      <Details summary="Praesent fringilla mollis nunc nec vehicula?">
        <p>
          Etiam mauris velit, molestie a egestas nec, volutpat hendrerit nunc.
          Duis a eros euismod est tincidunt rutrum pretium vel mauris. Praesent
          risus est, condimentum ac elit a, maximus faucibus nisi. Pellentesque
          elementum ullamcorper tellus eget pellentesque. Donec nec arcu tellus.
          Aliquam sit amet auctor ligula. Morbi neque lorem, scelerisque nec
          volutpat sit amet, tincidunt et erat. Integer pharetra justo non purus
          vehicula, ut porttitor nisi rutrum. Fusce eget gravida leo. Curabitur
          sit amet augue lorem. Aliquam augue ante, posuere eget malesuada in,
          volutpat vitae erat. Pellentesque imperdiet ipsum a sapien aliquam
          hendrerit. Proin diam ipsum, vulputate vitae purus vel, rhoncus
          vehicula turpis. Donec porttitor vitae tellus aliquet malesuada. Morbi
          luctus diam ac posuere bibendum. In aliquam felis non velit finibus
          hendrerit.
        </p>
      </Details>
      <Details summary="Aliquam id elit ullamcorper erat tempus volutpat?">
        <p>
          Aenean rutrum dictum tortor eget tempus. Vestibulum congue molestie
          neque sit amet suscipit. Nulla vel ornare nunc. Integer dignissim
          ipsum et urna auctor faucibus. Vestibulum ultricies volutpat purus, at
          consequat elit scelerisque sit amet. Sed sit amet convallis nisi.
          Quisque gravida, magna eget laoreet vulputate, nisi diam tincidunt
          ipsum, ac varius mauris purus eget nisl. Duis magna eros, ornare nec
          est eu, ullamcorper tincidunt ante. Phasellus risus ante, ullamcorper
          eu erat eu, blandit accumsan mauris. Praesent nulla ligula, varius
          vitae eros a, aliquet semper tellus.
        </p>
      </Details>
      <Details summary="Morbi iaculis ex ut nulla ullamcorper mollis?">
        <p>
          Nulla quis pulvinar leo, vitae rhoncus ex. Proin congue leo pharetra
          dignissim porta. Nullam urna libero, tristique vel risus vel, iaculis
          cursus neque. Donec scelerisque ligula ex, eget congue augue pretium
          et. Nulla dapibus sollicitudin tortor. Praesent finibus vitae dui non
          aliquet. In sollicitudin nisi at risus feugiat laoreet. Duis sit amet
          blandit diam, non congue ligula. Etiam sit amet nunc elementum,
          porttitor neque et, tempus nibh.
        </p>
      </Details>
      <Details summary="Mauris iaculis sagittis arcu?">
        <p>
          Vestibulum fringilla egestas turpis ut aliquet. Praesent vel viverra
          lectus, nec pharetra libero. Pellentesque leo nisi, elementum quis
          blandit nec, vulputate et enim. Sed venenatis sodales massa, in varius
          magna mattis sed. Pellentesque lectus eros, sagittis aliquet urna a,
          interdum euismod tortor. Etiam gravida sed libero eget porta. Duis non
          lacus justo. Donec dictum erat et sapien interdum aliquam. Sed mollis
          luctus dui, id tempus justo cursus eu. Cras vel scelerisque ipsum. In
          hac habitasse platea dictumst. Pellentesque tempus erat vel eleifend
          pharetra. Vivamus egestas et justo pulvinar bibendum. Curabitur est
          enim, ornare ac porttitor ut, venenatis in diam. Donec sodales in
          nulla sed ultrices.
        </p>
      </Details>
      <Details summary="Suspendisse finibus ultricies justo eu tristique?">
        <p>
          In vehicula, lorem sed convallis euismod, turpis nulla aliquam nisi, a
          ullamcorper lacus lectus eu leo. Nunc pharetra ullamcorper rutrum.
          Praesent placerat, nisi ut pulvinar efficitur, lacus arcu sagittis
          lacus, non eleifend odio erat a lorem. Duis sed ipsum sed ex finibus
          imperdiet in ut est. Sed suscipit, justo id sodales elementum, sem
          nunc convallis nisi, non cursus sem lectus et nulla. Phasellus
          tristique dolor quis mi tempus blandit. Mauris velit urna, auctor
          maximus blandit vitae, pharetra in turpis. Phasellus volutpat
          condimentum ullamcorper. Proin sit amet velit ipsum. Pellentesque
          sagittis, ante nec dignissim viverra, mauris eros posuere sapien, eu
          lobortis ex turpis vel metus. Nulla facilisi. Etiam in dapibus eros.
        </p>
      </Details>
      <Details summary="Aenean nec condimentum diam?">
        <p>
          Ut rutrum eros vehicula rutrum pretium. Maecenas luctus nunc sed sem
          imperdiet luctus. Nam sollicitudin nisl ac ligula auctor, mattis
          tempor turpis feugiat. Suspendisse iaculis, nunc nec porttitor
          tincidunt, tortor mauris luctus quam, ac facilisis odio lorem non
          diam. Fusce fringilla ex id dui luctus, at facilisis purus
          consectetur. Pellentesque vulputate at ipsum vitae condimentum. Donec
          sollicitudin elit id efficitur accumsan. Sed eu tempor arcu.
          Suspendisse nibh eros, vulputate ultricies purus id, faucibus
          tincidunt tortor. Mauris pellentesque aliquet rhoncus. Maecenas rutrum
          sem quis leo consequat, in volutpat lacus iaculis. Class aptent taciti
          sociosqu ad litora torquent per conubia nostra, per inceptos
          himenaeos. In hac habitasse platea dictumst. Aenean hendrerit
          hendrerit quam. Cras orci nibh, sollicitudin ac nunc sed, accumsan
          luctus sem.
        </p>
      </Details>
      <Details summary="Nullam volutpat nulla in tristique venenatis?">
        <p>
          Suspendisse tempus mauris ac libero molestie sagittis gravida nec sem.
          Morbi porttitor dictum est, sit amet tristique nunc efficitur
          fermentum. Morbi pretium laoreet nulla, dictum tempus quam finibus
          vel. Sed ut vehicula ipsum, at accumsan nibh. Fusce ac felis lectus.
          Cras malesuada a dui eget congue. Aenean felis massa, lobortis ac
          placerat ac, malesuada sed leo. In ultricies metus vitae pharetra
          pulvinar. Nullam cursus consequat lorem, gravida pulvinar magna tempus
          id.
        </p>
      </Details>
      <Details summary="Nulla facilisi?">
        <p>
          Aliquam consequat non lorem in tempor. Etiam felis erat, blandit ac
          interdum ut, luctus at quam. Pellentesque auctor odio id urna rhoncus,
          ut cursus mi hendrerit. Donec in massa non magna varius dignissim sit
          amet id lectus. Etiam mollis mollis finibus. Cras non metus mauris.
          Nullam facilisis consectetur purus, porttitor tincidunt augue.
        </p>
      </Details>
      <Details summary="Maecenas et placerat sapien?">
        <p>
          Ut volutpat ligula in velit aliquet bibendum. Nulla facilisi. Vivamus
          eget condimentum nulla, non ultricies turpis. Nullam pharetra odio
          ante, eget malesuada justo pretium eget. Pellentesque diam nisi,
          tincidunt nec purus at, dapibus vehicula magna. Sed id turpis nulla.
          Nulla facilisi. Pellentesque congue blandit laoreet. Cras at
          pellentesque nibh, ac vestibulum magna. Curabitur viverra, lectus non
          maximus sodales, velit tortor faucibus sapien, id sagittis leo massa
          id libero. Cras ac risus eget massa dictum fringilla. Mauris pretium
          nunc risus, vitae lobortis lectus placerat eu. Nulla facilisi. In hac
          habitasse platea dictumst. Duis vel lectus eros.
        </p>
      </Details>
      <Details summary="Mauris pharetra scelerisque nulla sit amet fringilla?">
        <p>
          Morbi sed egestas dolor, in vehicula magna. Suspendisse ullamcorper
          elit in tellus faucibus dignissim. Aliquam urna tellus, porttitor in
          dignissim at, consequat id urna. Donec auctor purus id nunc
          scelerisque, quis malesuada orci scelerisque. Vestibulum tempus
          imperdiet dolor, et suscipit erat scelerisque sed. Vestibulum dictum
          massa ut enim condimentum accumsan. Vestibulum feugiat congue nulla eu
          aliquet. Donec quam ligula, venenatis sed sem eu, facilisis maximus
          turpis. Sed malesuada dictum urna, sed imperdiet ex accumsan a.
          Vestibulum ante ipsum primis in faucibus orci luctus et ultrices
          posuere cubilia curae;
        </p>
      </Details>
      <Details summary="Quisque consectetur varius nibh?">
        <p>
          Suspendisse sit amet tortor elementum, ultrices lorem quis, luctus
          nisi. Nulla quis volutpat ex. Duis quis justo at nisi tincidunt
          sodales sed nec urna. Duis interdum risus at congue tristique.
          Pellentesque habitant morbi tristique senectus et netus et malesuada
          fames ac turpis egestas. Nullam ac dolor non nulla vestibulum
          elementum. Morbi ut mi sit amet enim tincidunt rutrum laoreet a urna.
          Vivamus at leo at nisl laoreet placerat. Sed a odio orci. Aenean
          gravida efficitur lectus quis fringilla. Pellentesque ullamcorper
          sodales risus, ac consequat tortor pretium id. Pellentesque habitant
          morbi tristique senectus et netus et malesuada fames ac turpis
          egestas. Duis tortor quam, commodo et sagittis ac, eleifend eget
          tortor. In a luctus elit. Donec quis nunc massa. Phasellus non ex
          lobortis, tincidunt nunc commodo, blandit odio.
        </p>
      </Details>
      <Details summary="Cras nec consequat nibh, id posuere nibh?">
        <p>
          Vestibulum tempus magna non aliquam pulvinar. Nam vestibulum nisi non
          aliquet lacinia. Praesent viverra cursus rhoncus. In hac habitasse
          platea dictumst. Quisque fringilla diam ac dui placerat, quis cursus
          turpis lobortis. Aenean sit amet quam tristique, auctor elit ut,
          porttitor magna. Quisque rhoncus posuere neque, ut elementum orci
          porta nec. In pharetra mollis volutpat. Fusce ullamcorper a quam quis
          faucibus. Ut varius, tortor id molestie mollis, lacus felis ultrices
          risus, imperdiet viverra massa libero in massa. Suspendisse maximus
          odio ac nisi posuere vehicula. Nunc hendrerit volutpat velit, non
          laoreet nibh laoreet sed.
        </p>
      </Details>
      <Details summary="Integer ut massa enim?">
        <p>
          Ut eget gravida dui. Sed eu commodo neque. Cras varius augue eu
          efficitur cursus. Cras tristique metus quis nibh finibus, nec ultrices
          nulla sagittis. Sed ac faucibus lectus. Sed interdum, risus id feugiat
          laoreet, ligula quam dignissim libero, in finibus dolor metus eget
          orci. Vivamus tristique odio id sapien mollis, et lacinia sapien
          pellentesque. Vivamus id bibendum ex. Aenean ut vehicula urna. Ut eu
          posuere nisi. Pellentesque habitant morbi tristique senectus et netus
          et malesuada fames ac turpis egestas. Nulla in ligula sem. Mauris in
          lorem scelerisque, tincidunt arcu ut, scelerisque mauris.
        </p>
      </Details>
      <Details summary="Nam maximus magna at lacinia mollis?">
        <p>
          Mauris at sem a risus laoreet semper. Pellentesque eu tempus nibh, et
          maximus arcu. Aenean eleifend tellus eu neque scelerisque, in feugiat
          ipsum convallis. Donec maximus quam lacus, vel maximus metus placerat
          at. Ut orci quam, lobortis a ante nec, sollicitudin condimentum neque.
          Curabitur aliquet sem eget scelerisque faucibus. Ut tempus risus orci,
          a rutrum metus vehicula eget. Morbi in euismod velit, sed tristique
          enim. Pellentesque eget metus rutrum sapien elementum pulvinar.
        </p>
      </Details>
      <Details summary="Mauris bibendum justo eu eleifend efficitur?">
        <p>
          Integer rutrum sollicitudin ipsum. Suspendisse eget gravida ipsum, sed
          suscipit orci. Nunc convallis faucibus aliquet. Sed porttitor
          ultricies aliquet. Duis id est ante. Nulla tellus libero, sollicitudin
          id eros eget, sagittis commodo tortor. Praesent posuere massa non
          tincidunt gravida. Vestibulum sit amet quam ut nisl laoreet euismod
          sit amet quis diam. Maecenas id nunc efficitur, vestibulum quam a,
          rutrum mi. Pellentesque porttitor nisl mauris. Vestibulum porta enim
          nibh, aliquam malesuada diam tincidunt et. Nam varius tristique
          fringilla. Proin pretium sapien dolor, ac ornare lacus luctus ut.
          Donec imperdiet metus ac aliquet fermentum. Proin aliquet ex ut porta
          luctus. Curabitur velit urna, fermentum at turpis vitae, mattis congue
          lorem.
        </p>
      </Details>
      <Details summary="Pellentesque quis feugiat tellus?">
        <p>
          In hac habitasse platea dictumst. Sed non lacus sed leo vulputate
          tincidunt. Donec sodales velit et sapien congue commodo. Phasellus
          turpis ipsum, porttitor ac commodo nec, sollicitudin a orci. Maecenas
          auctor neque nibh, quis pretium odio venenatis in. Pellentesque non
          porta lorem. Morbi et massa eget nulla sollicitudin tincidunt
          fermentum vitae enim. Sed ut maximus diam, interdum mattis est. Mauris
          cursus risus ut nulla commodo aliquet. Morbi id diam diam. Donec est
          urna, gravida sed mauris eu, scelerisque tincidunt risus. Sed aliquet
          odio non lacus venenatis, quis dapibus dolor cursus. Vestibulum
          rhoncus, odio facilisis volutpat vulputate, ex quam porttitor nisl,
          nec imperdiet orci orci at mauris. Integer ac placerat augue, et
          commodo libero. In a magna ac ex vehicula laoreet et in lacus. Integer
          eget metus justo.
        </p>
      </Details>
    </>
  );
}
