// sites/react-nextjs/src/app/(pages)/layout.tsx
import Header from "@/components/header/Header";
import s from "./layout.module.css";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Header />
      <main className={`page-width ${s.main}`}>{children}</main>
    </>
  );
}

// sites/qwik-qwik-city/src/routes/(pages)/layout.tsx
import { component$, Slot } from "@builder.io/qwik";
import Header from "~/components/header/header";
import styles from "./layout.module.css";

export default component$(() => {
  return (
    <>
      <Header />
      <main class={["page-width", styles.main]}>
        <Slot />
      </main>
    </>
  );
});
