// sites/vue-astro/src/components/LiveComponent.vue
<script setup lang="ts">
import liveData from "../assets/liveData.json" with { type: "json" };
import { ref, onMounted, onUnmounted } from "vue";

const INTERVAL = 1000;

const index = ref(0);
let timeoutId: number | NodeJS.Timeout;
function stepData() {
  index.value = (index.value + 1) % (liveData.length - 1);
  timeoutId = setTimeout(stepData, INTERVAL);
}

onMounted(() => {
  stepData();
});
onUnmounted(() => {
  clearTimeout(timeoutId);
});
</script>

<template>
  <table id="live-data">
    <tbody>
      <tr>
        <td>{{ liveData?.[index]?.[0] }}</td>
        <td>{{ liveData?.[index]?.[1] }}</td>
        <td>{{ liveData?.[index]?.[2] }}</td>
      </tr>
    </tbody>
  </table>
</template>

<style scoped>
#live-data {
  width: 100%;
  text-align: center;
  font-size: 2em;

  & td {
    height: 3.5em;
    border: 0.08em solid black;
    background-color: var(--color-secondary);
  }
}
</style>

// sites/svelte-astro/src/components/live.svelte
<script lang="ts">
	import liveData from '../assets/liveData.json' with { type: 'json' };
	import { onDestroy, onMount } from 'svelte';

	const INTERVAL = 1000;

	let index = $state(0);
	let timeoutId: number | NodeJS.Timeout;
	function stepData() {
		index = (index + 1) % (liveData.length - 1);
		timeoutId = setTimeout(stepData, INTERVAL);
	}

	onMount(() => {
		stepData();
	});
	onDestroy(() => {
		clearTimeout(timeoutId);
	});
</script>

<table id="live-data">
	<tbody>
		<tr>
			<td>{liveData[index][0]}</td>
			<td>{liveData[index][1]}</td>
			<td>{liveData[index][2]}</td>
		</tr>
	</tbody>
</table>

<style>
	#live-data {
		width: 100%;
		text-align: center;
		font-size: 2em;

		& td {
			height: 3.5em;
			border: 0.08em solid black;
			background-color: var(--color-secondary);
		}
	}
</style>
