// sites/svelte-astro/src/components/Tooltip.svelte
<script lang="ts">
  import type { Snippet } from "svelte";

  let { children }: { children: Snippet<[]> } = $props();

  let open = $state(false);

  let tooltip: HTMLElement | undefined = $state();
  let contents: HTMLElement | undefined = $state(undefined);

  function handleLightDismiss(event: MouseEvent) {
    const target = event.target as Node;
    if (
      contents &&
      target !== tooltip &&
      target !== contents &&
      !contents.contains(target)
    ) {
      open = false;
    }
  }
</script>

<svelte:document onclick={handleLightDismiss} />

<button class="tooltip" onclick={() => (open = !open)} bind:this={tooltip}>
  ?
</button>
{#if open}
  <span class="contents" bind:this={contents}>
    {@render children?.()}
  </span>
{/if}

<style>
  .tooltip {
    --size: 1.5em;

    padding: 0;
    border: 0.1em solid black;
    border-radius: 100%;
    width: var(--size);
    height: var(--size);
    background-color: var(--color-secondary);
    cursor: pointer;
  }
  .contents {
    display: block;
    position: fixed;
    max-width: 40rem;
    width: fit-content;
    height: fit-content;
    margin: auto;
    inset: 0px;
    padding: 0.5em;
    border: 0.1em solid black;
    border-radius: 0.3em;
    background-color: var(--color-secondary);
    box-shadow: var(--drop-shadow-large);
  }
</style>

// sites/angular-angular/src/lib/components/Tooltip.component.ts
import { Component, signal, ElementRef, HostListener } from '@angular/core';

@Component({
  selector: 'app-tooltip',
  standalone: true,
  imports: [],
  template: `
    <button class="tooltip" (click)="toggle()">?</button>

    @if (open()) {
      <div class="contents">
        <ng-content></ng-content>
      </div>
    }
  `,
  styles: [
    `
      .tooltip {
        --size: 1.5em;

        padding: 0;
        border: 0.1em solid black;
        border-radius: 100%;
        width: var(--size);
        height: var(--size);
        background-color: var(--color-secondary);
        cursor: pointer;
      }
      .contents {
        display: block;
        position: fixed;
        max-width: 40rem;
        width: fit-content;
        height: fit-content;
        margin: auto;
        inset: 0px;
        padding: 0.5em;
        border: 0.1em solid black;
        border-radius: 0.3em;
        background-color: var(--color-secondary);
        box-shadow: var(--drop-shadow-large);
      }
    `,
  ],
})
export class TooltipComponent {
  open = signal(false);

  constructor(private el: ElementRef<HTMLElement>) {}

  toggle() {
    this.open.update((v) => !v);
  }

  @HostListener('document:click', ['$event'])
  onDocClick(ev: MouseEvent) {
    if (!this.open()) return;
    if (!this.el.nativeElement.contains(ev.target as Node)) {
      this.open.set(false);
    }
  }
}
