// sites/preact-astro/src/components/details/Details.tsx
import { useSignal } from "@preact/signals";
import type { ComponentChildren } from "preact";
import s from "./Details.module.css";

interface Props {
  summary: string;
  children: ComponentChildren;
}

export default function Details({ summary, children }: Props) {
  const open = useSignal(false);
  const toggleOpen = () => {
    open.value = !open.value;
  };
  return (
    <div className={`details ${s.details} ${open.value ? s.open : ""}`}>
      <button className={`summary ${s.summary}`} onClick={toggleOpen}>
        {summary}
      </button>
      {open.value && <div className={`contents ${s.contents}`}>{children}</div>}
    </div>
  );
}

// sites/qwik-qwik-city/src/components/details/details.tsx
import { component$, Slot, useSignal } from "@builder.io/qwik";
import styles from "./details.module.css";

interface ItemProps {
  summary: string;
}

export default component$<ItemProps>(({ summary }) => {
  const open = useSignal(false);

  return (
    <>
      <div class={["details", styles.details]}>
        <button
          class={[
            "summary",
            styles.summary,
            open.value ? styles["open-summary"] : "",
          ]}
          onClick$={() => (open.value = !open.value)}
        >
          {summary}
        </button>
        {open.value && (
          <div class={["contents", styles.contents]}>
            <Slot />
          </div>
        )}
      </div>
    </>
  );
});
