// sites/react-nextjs/src/components/Details.tsx
"use client";
import { ReactNode, useState } from "react";
import s from "./Details.module.css";

interface Props {
  summary: string;
  children: ReactNode;
}

export default function Details({ summary, children }: Props) {
  const [open, setOpen] = useState(false);
  const toggleOpen = () => setOpen((o) => !o);

  return (
    <div className={`${s.details} ${open ? s.open : ""}`}>
      <button className={s.summary} onClick={toggleOpen}>
        {summary}
      </button>
      {open && <div className={s.contents}>{children}</div>}
    </div>
  );
}

// sites/solid-vite/src/components/Details.tsx
import { type JSX, createSignal, Show } from "solid-js";
import styles from "./Details.module.css";

export default function Details(props: {
  summary: string;
  children: JSX.Element;
}) {
  const [open, setOpen] = createSignal(false);

  return (
    <div class={`details ${styles.details}`}>
      <button
        class={`summary ${styles.summary} ${open() ? styles["open-summary"] : ""}`}
        onclick={() => setOpen((previous) => !previous)}
      >
        {props.summary}
      </button>
      <Show when={open()}>
        <div class={`contents ${styles.contents}`}>{props.children}</div>
      </Show>
    </div>
  );
}
