// sites/react-vite-react-router-declarative/src/components/live/Live.tsx
"use client";
import liveData from "../../assets/liveData.json" with { type: "json" };
import s from "./Live.module.css";
import { useEffect, useState } from "react";

export default function Live() {
  const INTERVAL = 1000 as const;

  const [index, setIndex] = useState(0);

  useEffect(() => {
    let timeoutId: number;
    function stepData() {
      setIndex((curr) => (curr + 1) % (liveData.length - 1));
      timeoutId = setTimeout(stepData, INTERVAL);
    }
    stepData();
    return () => {
      clearTimeout(timeoutId);
    };
  }, []);

  return (
    <table id="live-data" className={s.liveData}>
      <tbody>
        <tr>
          <td>{liveData?.[index]?.[0]}</td>
          <td>{liveData?.[index]?.[1]}</td>
          <td>{liveData?.[index]?.[2]}</td>
        </tr>
      </tbody>
    </table>
  );
}

// sites/solid-vite/src/components/Live.tsx
import liveData from "../assets/liveData.json" with { type: "json" };
import { createSignal, onCleanup, onMount } from "solid-js";
import styles from "./Live.module.css";

const INTERVAL = 800;

export default function Live() {
  const [index, setIndex] = createSignal(0);
  let timeoutId: any;
  function stepData() {
    setIndex((index() + 1) % liveData.length);
    timeoutId = setTimeout(stepData, INTERVAL);
  }

  onMount(() => {
    stepData();
  });
  onCleanup(() => {
    clearTimeout(timeoutId);
  });

  return (
    <table id="live-data" class={styles["live-data"]}>
      <tbody>
        <tr>
          <td>{liveData?.[index()]?.[0]}</td>
          <td>{liveData?.[index()]?.[1]}</td>
          <td>{liveData?.[index()]?.[2]}</td>
        </tr>
      </tbody>
    </table>
  );
}
