// sites/solid-vite/src/components/Tooltip.tsx
import { type JSX, createSignal, onCleanup, onMount, Show } from "solid-js";
import { isServer } from "solid-js/web";
import styles from "./Tooltip.module.css";

export default function Tooltip(props: { children: JSX.Element }) {
  const [open, setOpen] = createSignal(false);
  let tooltipRef: HTMLButtonElement | undefined;
  let contentsRef: HTMLSpanElement | undefined;

  function handleLightDismiss(event: MouseEvent) {
    const target = event.target as Node;
    if (
      contentsRef &&
      target !== tooltipRef &&
      target !== contentsRef &&
      !contentsRef.contains(target)
    ) {
      setOpen(false);
    }
  }

  onMount(() => {
    if (!isServer) document.addEventListener("click", handleLightDismiss);
  });

  onCleanup(() => {
    if (!isServer) document.removeEventListener("click", handleLightDismiss);
  });

  return (
    <>
      {" "}
      <button
        class={`tooltip ${styles.tooltip}`}
        onclick={() => setOpen((previous) => !previous)}
        ref={tooltipRef}
      >
        ?
      </button>
      <Show when={open()}>
        <span class={`contents ${styles.contents}`} ref={contentsRef}>
          {props.children}
        </span>
      </Show>{" "}
    </>
  );
}

// sites/react-nextjs/src/components/Tooltip.tsx
"use client";
import { ReactNode, RefObject, useEffect, useRef, useState } from "react";
import s from "./Tooltip.module.css";

interface Props {
  children: ReactNode;
}

export default function Tooltip({ children }: Props) {
  const [open, setOpen] = useState(false);
  const toggleOpen = () => setOpen((o) => !o);

  const tooltip: RefObject<HTMLButtonElement | null> = useRef(null);
  const contents: RefObject<HTMLSpanElement | null> = useRef(null);

  useEffect(() => {
    function handleLightDismiss(event: MouseEvent) {
      if (tooltip.current === null || contents.current === null) return;

      const target = event.target as Node;
      if (
        target !== tooltip.current &&
        target !== contents.current &&
        !contents.current?.contains(target)
      ) {
        setOpen(false);
      }
    }

    // Attach the event listener to the document
    document.addEventListener("click", handleLightDismiss);

    // Cleanup on unmount
    return () => {
      document.removeEventListener("click", handleLightDismiss);
    };
  }, []);

  return (
    <>
      {" "}
      <button className={s.tooltip} onClick={toggleOpen} ref={tooltip}>
        ?
      </button>{" "}
      {open && (
        <span className={s.contents} ref={contents}>
          {children}
        </span>
      )}
    </>
  );
}
