// sites/solid-vite/src/components/Details.tsx
import { type JSX, createSignal, Show } from "solid-js";
import styles from "./Details.module.css";

export default function Details(props: {
  summary: string;
  children: JSX.Element;
}) {
  const [open, setOpen] = createSignal(false);

  return (
    <div class={`details ${styles.details}`}>
      <button
        class={`summary ${styles.summary} ${open() ? styles["open-summary"] : ""}`}
        onclick={() => setOpen((previous) => !previous)}
      >
        {props.summary}
      </button>
      <Show when={open()}>
        <div class={`contents ${styles.contents}`}>{props.children}</div>
      </Show>
    </div>
  );
}

// sites/react-astro/src/components/Details.tsx
import { type ReactNode, useCallback, useState } from "react";
import s from "./Details.module.css";

interface Props {
  summary: string;
  children: ReactNode;
}

export default function Details({ summary, children }: Props) {
  const [open, setOpen] = useState(false);
  const toggleOpen = useCallback(() => {
    setOpen((o) => !o);
  }, []);

  return (
    <div className={`details ${s.details} ${open ? s.open : ""}`}>
      <button className={`summary ${s.summary}`} onClick={toggleOpen}>
        {summary}
      </button>
      {open && <div className={`contents ${s.contents}`}>{children}</div>}
    </div>
  );
}
