// sites/solid-vite/src/index.tsx
/* @refresh reload */
import { render } from "solid-js/web";
import { Router, Route } from "@solidjs/router";
import BaseLayout from "./layouts/Base.tsx";
import HomePage from "./pages/Home.tsx";
import PagesLayout from "./layouts/Pages.tsx";
import Static1Page from "./pages/Static1.tsx";
import Static2Page from "./pages/Static2.tsx";
import LivePage from "./pages/Live.tsx";
import TooltipsPage from "./pages/Tooltips.tsx";
import FaqPage from "./pages/Faq.tsx";
import ListPage from "./pages/List.tsx";
import "./index.css";

render(
  () => (
    <Router>
      <Route path="/" component={BaseLayout}>
        <Route path="/" component={HomePage} />
        <Route path="/" component={PagesLayout}>
          <Route path="/static-1/" component={Static1Page} />
          <Route path="/static-2/" component={Static2Page} />
          <Route path="/live/" component={LivePage} />
          <Route path="/tooltips/" component={TooltipsPage} />
          <Route path="/faq/" component={FaqPage} />
          <Route path="/list/" component={ListPage} />
        </Route>
      </Route>
    </Router>
  ),
  document.getElementById("root")!,
);

// sites/react-vite-react-router-declarative/src/main.tsx
import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import { BrowserRouter, Routes, Route } from "react-router";

import ScrollResetWrapper from "@/components/wrappers/scroll-reset/scroll-reset";
import HeaderLayout from "@/app/header-layout";
import FooterLayout from "@/app/footer-layout";
import Home from "@/app/index.tsx";
import Faq from "@/app/faq/page";
import List from "@/app/list/page";
import Live from "@/app/live/page";
import Static1 from "@/app/static-1/page";
import Static2 from "@/app/static-2/page";
import Tooltips from "@/app/tooltips/page";

import "@/app/globals.css";

createRoot(document.getElementById("root")!).render(
  <StrictMode>
    <BrowserRouter>
      <ScrollResetWrapper>
        <Routes>
          <Route element={<FooterLayout />}>
            <Route path="/" element={<Home />} />
            <Route element={<HeaderLayout />}>
              <Route path="faq" element={<Faq />} />
              <Route path="list" element={<List />} />
              <Route path="live" element={<Live />} />
              <Route path="static-1" element={<Static1 />} />
              <Route path="static-2" element={<Static2 />} />
              <Route path="tooltips" element={<Tooltips />} />
            </Route>
          </Route>
        </Routes>
      </ScrollResetWrapper>
    </BrowserRouter>
  </StrictMode>,
);
